### ISSUE TITLE
Could not connect to rootkit.

### ISSUE THREAD

**Issue by WilleLX1** [ZeroMemoryEx/Chaos-Rootkit#13]
**Subject:** Unable to Connect to Rootkit - "INVALID_HANDLE_VALUE" Error

**Description:**

I've encountered an issue while trying to use the Chaos Rootkit. I followed the steps below:

1. Downloaded all the necessary rootkit files from the release page, including "Chaos-Rootkit.sys," "imgui.ini," and "ring3-gui.exe."

2. Launched "ring3-gui.exe."

3. Clicked on the "Connect to rootkit" button.

However, each time I attempt to connect to the rootkit, I encounter the following error message in the "ring3-gui.exe" console:

**INVALID_HANDLE_VALUE**

I would appreciate any help or guidance on resolving this issue. Thank you in advance for your assistance!

Best regards,
WilleLX1

**Comment by ZeroMemoryEx** [comment]
Hello @WilleLX1 , the rootkit currently works only when **DSE** is disabled, which will be added in the future. You can disable DSE by opening Command Prompt as an administrator and running the following command: **bcdedit /set testsigning off**, then restart, and it should work. Note that the GUI version is currently marked as **unstable**, which will be fixed in the next updates. Happy hacking!

**Comment by WilleLX1** [comment]
Thanks for the great response!

**Comment by ZeroMemoryEx** [comment]
anytime ,happy to help !!
